import {createHmac,randomUUID} from 'node:crypto';
const env=()=>({url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY});
const configured=e=>Boolean(e.url&&e.key);
async function db(path,options={}){const e=env();const response=await fetch(`${e.url.replace(/\/$/,'')}/rest/v1/${path}`,{...options,headers:{apikey:e.key,Authorization:`Bearer ${e.key}`,'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('공유 저장소에 연결하지 못했어요. 설정을 확인해 주세요.');const raw=await response.text();return raw?JSON.parse(raw):null;}
function image(value){if(value===null||value===undefined)return null;if(typeof value!=='string'||value.length>400000||!/^data:image\/(png|webp|jpeg|gif);base64,[A-Za-z0-9+/=]+$/.test(value))throw new Error('지원하지 않거나 너무 큰 이미지예요.');return value;}
function record(body){if(!['건호','주훈'].includes(body.author)||!['diary','photo','quote','music'].includes(body.kind)||typeof body.text!=='string'||body.text.length>5000)throw new Error('기록 형식을 확인해 주세요.');const row={author:body.author,kind:body.kind,text:body.text.trim(),image:image(body.image)};if(!row.text&&!row.image)throw new Error('내용이나 사진을 넣어 주세요.');return row;}
function validId(value){if(!/^[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}$/i.test(value||''))throw new Error('기록을 찾을 수 없어요.');return value;}
function beforeQuery(req){const before=req.query?.before||new URL(req.url,'http://localhost').searchParams.get('before');if(!before)return '';if(!/^\d{4}-\d{2}-\d{2}T/.test(before)||Number.isNaN(Date.parse(before)))throw new Error('날짜 형식을 확인해 주세요.');return `&created_at=lt.${encodeURIComponent(before)}`;}
async function page(req,guest=false){const channel=req.query?.channel||'diary';if(!guest&&!['diary','music'].includes(channel))throw new Error('채널을 확인해 주세요.');const limit=guest?30:8,table=guest?'room_guest_messages':'room_messages',filter=guest?'':channel==='music'?'&kind=eq.music':'&kind=in.(diary,photo,quote)';const rows=await db(`${table}?select=*&order=created_at.desc,id.desc&limit=${limit+1}${filter}${beforeQuery(req)}`);const messages=rows.slice(0,limit);const cursor=messages.at(-1)?.created_at||null;return {posts:messages.reverse(),more:rows.length>limit,nextCursor:cursor};}
async function rateAllowed(req,e,scope){const ip=req.headers['x-vercel-forwarded-for']||req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown';const key=createHmac('sha256',e.key).update(scope+':'+String(ip).split(',')[0]).digest('hex');return await db('rpc/room_login_attempt',{method:'POST',body:JSON.stringify({p_key:key})});}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');const send=(status,data)=>res.status(status).json(data);try{const e=env(),action=req.query?.action||new URL(req.url,'http://localhost').searchParams.get('action');if(req.method==='GET'&&action==='config')return send(200,{configured:configured(e),authenticated:configured(e),public:true});if(!configured(e))return send(503,{error:'Supabase 연결 설정이 필요해요.'});if(req.method!=='GET'){const origin=req.headers.origin;if(origin){let valid=false;try{valid=new URL(origin).host===req.headers.host}catch{}if(!valid)return send(403,{error:'사이트에서 다시 시도해 주세요.'})}if(!String(req.headers['content-type']||'').startsWith('application/json'))return send(415,{error:'지원하지 않는 요청이에요.'});}
if(req.method==='POST'&&action!=='guest_post'&&!await rateAllowed(req,e,'public-write'))return send(429,{error:'작성 횟수가 많아요. 15분 후 다시 시도해 주세요.'});
const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{};if(Buffer.byteLength(JSON.stringify(body))>1000000)return send(413,{error:'첨부 파일 크기를 줄여 주세요.'});
if(action==='guest_list'&&req.method==='GET')return send(200,await page(req,true));
if(action==='guest_post'&&req.method==='POST'){if(typeof body.author!=='string'||body.author.trim().length<1||body.author.trim().length>24||typeof body.text!=='string'||!body.text.trim()||body.text.length>2000)throw new Error('닉네임은 24자, 방명록은 2,000자까지 입력할 수 있어요.');if(!await rateAllowed(req,e,'guest'))return send(429,{error:'작성 횟수가 많아요. 15분 후 다시 시도해 주세요.'});const rows=await db('room_guest_messages',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id:randomUUID(),author:body.author.trim(),text:body.text.trim()})});return send(200,{post:rows[0]});}
if(action==='profiles_get'&&req.method==='GET'){return send(200,{profiles:await db('room_member_profiles?select=name,avatar')});}
if(action==='profiles_save'&&req.method==='POST'){if(!Array.isArray(body.profiles)||body.profiles.length!==2||new Set(body.profiles.map(p=>p.name)).size!==2)throw new Error('프로필 형식을 확인해 주세요.');const rows=body.profiles.map(p=>{if(!['건호','주훈'].includes(p.name)||p.avatar&&p.avatar.length>200000)throw new Error('프로필 형식을 확인해 주세요.');return {name:p.name,avatar:image(p.avatar)};});await db('room_member_profiles?on_conflict=name',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(rows)});return send(200,{ok:true});}
if(action==='list'&&req.method==='GET')return send(200,await page(req));
if(action==='post'&&req.method==='POST'){const rows=await db('room_messages',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({...record(body),id:randomUUID()})});return send(200,{post:rows[0]});}
if(action==='edit'&&req.method==='POST'){await db(`room_messages?id=eq.${validId(body.id)}`,{method:'PATCH',body:JSON.stringify(record(body))});return send(200,{ok:true});}
if(['delete','guest_delete'].includes(action)&&req.method==='POST'){await db(`${action==='delete'?'room_messages':'room_guest_messages'}?id=eq.${validId(body.id)}`,{method:'DELETE'});return send(200,{ok:true});}
return send(405,{error:'지원하지 않는 요청이에요.'});
}catch(error){const allowed=['프로필 형식을 확인해 주세요.','공유 저장소에 연결하지 못했어요. 설정을 확인해 주세요.','지원하지 않거나 너무 큰 이미지예요.','기록 형식을 확인해 주세요.','내용이나 사진을 넣어 주세요.','기록을 찾을 수 없어요.','날짜 형식을 확인해 주세요.','채널을 확인해 주세요.','닉네임은 24자, 방명록은 2,000자까지 입력할 수 있어요.'];return send(400,{error:allowed.includes(error.message)?error.message:'요청을 처리하지 못했어요. 잠시 후 다시 시도해 주세요.'});}}
